import type { Patient } from "@/graphql/types";

export const mockPatientData: Patient[] = [
  {
    id: "1",
    name: "Emily Johnson",
    age: 24,
    gender: "Female",
    conditions: [],
    lastVisit: "2025-05-14",
    status: "Pending",
    visitType: "Initial consult",
    avatar: "http://static.photos/people/200x200/2",
  },
  {
    id: "2",
    name: "John Smith",
    age: 44,
    gender: "Male",
    conditions: ["Diabetes"],
    lastVisit: "2025-09-10",
    status: "Active",
    visitType: "Follow up",
    avatar: "http://static.photos/people/200x200/3",
  },
  {
    id: "3",
    name: "Ava Cruz",
    age: 27,
    gender: "Female",
    conditions: ["Asthma"],
    lastVisit: "2025-09-20",
    status: "Active",
    visitType: "Annual checkup",
    avatar: null,
  },
  {
    id: "4",
    name: "Leo Santos",
    age: 53,
    gender: "Male",
    conditions: ["COPD"],
    lastVisit: "2025-09-18",
    status: "Active",
    visitType: "Follow up",
    avatar: "http://static.photos/people/200x200/4",
  },
  {
    id: "5",
    name: "Mei Lin",
    age: 40,
    gender: "Female",
    conditions: ["Migraine"],
    lastVisit: "2025-09-12",
    status: "Active",
    visitType: "Telemedicine",
    avatar: "http://static.photos/people/200x200/5",
  },
  {
    id: "6",
    name: "Ravi Kumar",
    age: 35,
    gender: "Male",
    conditions: ["Allergy"],
    lastVisit: "2025-09-05",
    status: "Active",
    visitType: "Lab results",
    avatar: "",
  },
  {
    id: "7",
    name: "Sam Lee",
    age: 29,
    gender: "Other",
    conditions: ["Anxiety"],
    lastVisit: "2025-09-22",
    status: "Active",
    visitType: "Follow up",
    avatar: "http://static.photos/people/200x200/6",
  },
  {
    id: "8",
    name: "Carlos Dela Cruz",
    age: 61,
    gender: "Male",
    conditions: ["Arthritis"],
    lastVisit: "2025-08-28",
    status: "Inactive",
    visitType: "Annual checkup",
    avatar: "http://static.photos/people/200x200/7",
  },
  {
    id: "9",
    name: "Sophia Reyes",
    age: 46,
    gender: "Female",
    conditions: ["Diabetes"],
    lastVisit: "2025-09-03",
    status: "Active",
    visitType: "Follow up",
    avatar: null,
  },
  {
    id: "10",
    name: "Liam Park",
    age: 31,
    gender: "Male",
    conditions: [],
    lastVisit: "2025-10-01",
    status: "New",
    visitType: "Initial consult",
    avatar: "http://static.photos/people/200x200/8",
  },
  {
    id: "11",
    name: "Olivia Chen",
    age: 28,
    gender: "Female",
    conditions: ["Anxiety"],
    lastVisit: "2025-09-25",
    status: "Active",
    visitType: "Telemedicine",
    avatar: "",
  },
  {
    id: "12",
    name: "Ethan Garcia",
    age: 52,
    gender: "Male",
    conditions: ["Hypertension"],
    lastVisit: "2025-09-16",
    status: "Active",
    visitType: "Follow up",
    avatar: "http://static.photos/people/200x200/9",
  },
  {
    id: "13",
    name: "Mia Patel",
    age: 33,
    gender: "Female",
    conditions: [],
    lastVisit: "2025-09-11",
    status: "Pending",
    visitType: "Initial consult",
    avatar: null,
  },
  {
    id: "14",
    name: "Aarav Sharma",
    age: 48,
    gender: "Male",
    conditions: ["Back Pain"],
    lastVisit: "2025-08-31",
    status: "Active",
    visitType: "Lab results",
    avatar: "http://static.photos/people/200x200/10",
  },
  {
    id: "15",
    name: "Harper Nguyen",
    age: 22,
    gender: "Female",
    conditions: ["Asthma"],
    lastVisit: "2025-09-29",
    status: "Active",
    visitType: "Annual checkup",
    avatar: "",
  },
  {
    id: "16",
    name: "Lucas Kim",
    age: 39,
    gender: "Male",
    conditions: ["Depression"],
    lastVisit: "2025-09-21",
    status: "Active",
    visitType: "Follow up",
    avatar: "http://static.photos/people/200x200/11",
  },
  {
    id: "17",
    name: "Isabella Flores",
    age: 55,
    gender: "Female",
    conditions: ["Arthritis"],
    lastVisit: "2025-09-06",
    status: "Discharged",
    visitType: "Post-op",
    avatar: null,
  },
  {
    id: "18",
    name: "Mason Rivera",
    age: 45,
    gender: "Male",
    conditions: ["Hyperlipidemia"],
    lastVisit: "2025-09-27",
    status: "Active",
    visitType: "Follow up",
    avatar: "http://static.photos/people/200x200/12",
  },
  {
    id: "19",
    name: "Avery Gomez",
    age: 30,
    gender: "Other",
    conditions: ["Migraine"],
    lastVisit: "2025-09-19",
    status: "Active",
    visitType: "Telemedicine",
    avatar: "",
  },
  {
    id: "20",
    name: "James Anderson",
    age: 63,
    gender: "Male",
    conditions: ["Chronic Kidney Disease"],
    lastVisit: "2025-09-02",
    status: "Active",
    visitType: "Lab results",
    avatar: "http://static.photos/people/200x200/13",
  },
  {
    id: "21",
    name: "Charlotte Perez",
    age: 36,
    gender: "Female",
    conditions: [],
    lastVisit: "2025-09-24",
    status: "New",
    visitType: "Initial consult",
    avatar: "http://static.photos/people/200x200/14",
  },
  {
    id: "22",
    name: "Benjamin Lee",
    age: 26,
    gender: "Male",
    conditions: ["Asthma"],
    lastVisit: "2025-10-02",
    status: "Active",
    visitType: "Annual checkup",
    avatar: null,
  },
  {
    id: "23",
    name: "Amelia Torres",
    age: 41,
    gender: "Female",
    conditions: ["Hypertension"],
    lastVisit: "2025-09-09",
    status: "Active",
    visitType: "Follow up",
    avatar: "",
  },
  {
    id: "24",
    name: "Elijah Scott",
    age: 58,
    gender: "Male",
    conditions: ["Diabetes"],
    lastVisit: "2025-09-13",
    status: "Active",
    visitType: "Follow up",
    avatar: "http://static.photos/people/200x200/15",
  },
  {
    id: "25",
    name: "Abigail Morales",
    age: 29,
    gender: "Female",
    conditions: ["Anemia"],
    lastVisit: "2025-09-26",
    status: "Active",
    visitType: "Lab results",
    avatar: "http://static.photos/people/200x200/16",
  },
  {
    id: "26",
    name: "Henry Zhang",
    age: 34,
    gender: "Male",
    conditions: ["GERD"],
    lastVisit: "2025-09-08",
    status: "Active",
    visitType: "Follow up",
    avatar: "",
  },
  {
    id: "27",
    name: "Evelyn Cruz",
    age: 47,
    gender: "Female",
    conditions: [],
    lastVisit: "2025-09-23",
    status: "Pending",
    visitType: "Initial consult",
    avatar: "http://static.photos/people/200x200/17",
  },
  {
    id: "28",
    name: "Daniel Baker",
    age: 51,
    gender: "Male",
    conditions: ["COPD"],
    lastVisit: "2025-08-30",
    status: "Active",
    visitType: "Follow up",
    avatar: null,
  },
  {
    id: "29",
    name: "Zoey Carter",
    age: 33,
    gender: "Female",
    conditions: ["Anxiety"],
    lastVisit: "2025-09-04",
    status: "Active",
    visitType: "Telemedicine",
    avatar: "http://static.photos/people/200x200/18",
  },
  {
    id: "30",
    name: "Jackson Young",
    age: 42,
    gender: "Male",
    conditions: ["Back Pain"],
    lastVisit: "2025-09-20",
    status: "Active",
    visitType: "Annual checkup",
    avatar: "",
  },
];
